### ISSUE TITLE
No ST-LINK detected error when trying to debug

### ISSUE THREAD

**Issue by mikemorrell2** [flathub/com.st.STM32CubeIDE#2]
I installed STM32CubeIDE v1.4.0 from flathub on Fedora Silverblue 32 (32.20200914.0). I connected ST NUCLEO F030R8 board to USB and I try to run debugger on my project. I get "ST-LINK firmware verification" dialog box popup with message "No ST-LINK detected! Please connect ST-LINK and restart debug session." This board works okay on Windows 10 and Ubuntu 20.04 with deb version of STM32CubeIDE so I know it is not a hardware issue.

**Comment by FakeShemp** [comment]
I think you at least have to plug any devices in before starting the app. Hotplugging is not supported.

**Comment by mikemorrell2** [comment]
> I think you at least have to plug any devices in before starting the app. Hotplugging is not supported.

Yes, I did plug it in before launching STM32CubeIDE app. This does not appear to be the issue.

**Comment by FakeShemp** [comment]
It'd be nice if you could run `flatpak run com.st.STM32CubeIDE` and post the logs that spit out. Thank you for testing :)

**Comment by mikemorrell2** [comment]
I don't get any logs on the command line when I run it or when I start debugging. I do get some eclipse logs when I start-up STM32CubeIDE. There is an error log for each of the ttyXX devices, I posted one here as an example. I am using the devault debug run configuration that is set to launch a local GDB server. Not sure if the server is getting started or not. What more can I do to help test this? Is it working for anyone else currently? Maybe it is a permission issue, SELinux config issue, or is it a missing file or path config issue. Not sure what steps to try to test further. Do I need to add some options to the flatpak command line to get more logs?

eclipse.buildId=Version 1.4.0
java.version=1.8.0_252
java.vendor=AdoptOpenJDK
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

com.st.stm32cube.ide.mpu.remote.serial
Error
Thu Sep 17 11:50:30 EDT 2020
Failed to parse udevadm output for /dev/ttyACM0

java.io.IOException: Cannot run program "udevadm": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.st.stm32cube.ide.mpu.remote.serial.internal.SerialPortProviderLinux$PortInfo.hasValidManufacturer(SerialPortProviderLinux.java:84)
	at com.st.stm32cube.ide.mpu.remote.serial.internal.SerialPortProviderLinux$PortInfo.validate(SerialPortProviderLinux.java:68)
	at com.st.stm32cube.ide.mpu.remote.serial.internal.SerialPortProviderLinux.run(SerialPortProviderLinux.java:156)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 5 more

**Comment by mikemorrell2** [comment]
I ran flatpak with verbose flag. Here is the start-up logs. There were no additional logs when I launch debug.

[mike@mustang ~]$ flatpak run -v com.st.STM32CubeIDE
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /var/home/mike/.local/share/flatpak
F: Opening user flatpak installation at path /var/home/mike/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /var/home/mike/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 3984786414
F: Allocated instance id 4247325220
F: Add defaults in dir /com/st/STM32CubeIDE/
F: Add locks in dir /com/st/STM32CubeIDE/
F: Allowing host-fs access
F: Allowing homedir access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/var/home/mike/.config/pulse/client.conf': Error opening file /var/home/mike/.config/pulse/client.conf: No such file or directory
F: Allowing session-dbus access
F: Running 'bwrap --args 38 xdg-dbus-proxy --args=40'
F: Running 'bwrap --args 38 stm32cubeide'

**Comment by erazemk** [comment]
+1 with this problem, plugged the board before starting the flatpak, here's the output:

```sh
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/erazemk/.local/share/flatpak
F: Opening user flatpak installation at path /home/erazemk/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/erazemk/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 1158913066
F: Allocated instance id 2363508423
F: Add defaults in dir /com/st/STM32CubeIDE/
F: Add locks in dir /com/st/STM32CubeIDE/
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/erazemk/.config/pulse/client.conf': Error opening file /home/erazemk/.config/pulse/client.conf: No such file or directory
F: Allowing session-dbus access
F: bwrap --args 36 = --ro-bind /boot /boot --ro-bind /dev /dev --ro-bind /home /home --ro-bind /proc /proc --bind /run /run --ro-bind /sys /sys --ro-bind /root /root --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/sbin /sbin --ro-bind /etc /etc --ro-bind '/lost+found' '/lost+found' --ro-bind /media /media --ro-bind /mnt /mnt --ro-bind /opt /opt --ro-bind /srv /srv --bind /tmp /tmp --ro-bind /usr /usr --bind /var /var --bind /run/user/1000/.dbus-proxy/ /run/user/1000/.dbus-proxy/ --file 34 /.flatpak-info
F: bwrap --args 38 = --fd=37 unix:abstract=0004f /run/user/1000/.dbus-proxy/a11y-bus-proxy-QL5TS0 --filter --sloppy-names --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Embed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Socket.Unembed@/org/a11y/atspi/accessible/root --call=org.a11y.atspi.Registry=org.a11y.atspi.Registry.GetRegisteredEvents@/org/a11y/atspi/registry --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetKeystrokeListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.GetDeviceEventListeners@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersSync@/org/a11y/atspi/registry/deviceeventcontroller --call=org.a11y.atspi.Registry=org.a11y.atspi.DeviceEventController.NotifyListenersAsync@/org/a11y/atspi/registry/deviceeventcontroller
F: Running 'bwrap --args 36 xdg-dbus-proxy --args=38'
F: bwrap --args 36 = --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files /usr --lock-file /usr/.ref --ro-bind /var/lib/flatpak/app/com.st.STM32CubeIDE/x86_64/stable/52bbd14a96597dafa2fe62b99ba0d30dcf4138e87ffda0992f688460bfe0a255/files /app --lock-file /app/.ref --tmpfs /usr/lib/x86_64-linux-gnu/GL --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.GL.default/x86_64/20.08/13b663698f585858f14e30f70bbd07b07e3d4825617115e803acd4d4a2ed5795/files /usr/lib/x86_64-linux-gnu/GL/default --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/20.08/e21a5a785d1f04068a57705cf2444cf92178d27e1c08a543c6fbeaf8d2800eb2/files /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver --ro-bind /var/lib/flatpak/runtime/org.freedesktop.Platform.openh264/x86_64/2.0/73f998362a6fc0d57e0c7e83e928d32b0ec14d10d0d94291033976bdcecc6b6b/files /usr/lib/x86_64-linux-gnu/openh264 --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform.Locale/x86_64/3.38/cfee66614ff3d7fea5a4df1f817e8fdad4190e68ade3325eb72da26e5f263e3f-en-sl/files /usr/share/runtime/locale --tmpfs /usr/share/runtime/share/themes --ro-bind /var/lib/flatpak/runtime/org.gtk.Gtk3theme.Adwaita-dark/x86_64/3.22/7c055bbc0667524f34ca715abd67473480de93a176797a8fe4b7f7a71c4e3324/files /usr/share/runtime/share/themes/Adwaita-dark/gtk-3.0 --ro-bind-data 15 /run/flatpak/ld.so.conf.d/runtime-001-org.freedesktop.Platform.GL.default.conf --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/intel_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/icd.d/radeon_icd.x86_64.json /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/glvnd/egl_vendor.d/50_mesa.json /usr/lib/x86_64-linux-gnu/GL/glvnd/egl_vendor.d/50_mesa.json --symlink /usr/lib/x86_64-linux-gnu/GL/default/OpenCL/vendors/mesa.icd /usr/lib/x86_64-linux-gnu/GL/OpenCL/vendors/mesa.icd --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i915_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i915_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/i965_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/i965_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/iris_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/iris_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/kms_swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/kms_swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libgallium_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libgallium_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/libmesa_dri_drivers.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/libmesa_dri_drivers.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/nouveau_vieux_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/nouveau_vieux_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r200_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r200_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r300_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r300_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/r600_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/r600_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeon_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeon_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/radeonsi_drv_video.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/radeonsi_drv_video.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/swrast_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/swrast_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/virtio_gpu_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/virtio_gpu_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/vmwgfx_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/vmwgfx_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/zink_dri.so /usr/lib/x86_64-linux-gnu/GL/lib/dri/zink_dri.so --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1 --symlink /usr/lib/x86_64-linux-gnu/GL/default/lib/d3d/d3dadapter9.so.1.0.0 /usr/lib/x86_64-linux-gnu/GL/lib/d3d/d3dadapter9.so.1.0.0 --symlink /usr/lib/x86_64-linux-gnu/GL/default/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json /usr/lib/x86_64-linux-gnu/GL/vulkan/explicit_layer.d/VkLayer_MESA_overlay.json --ro-bind-data 16 /run/flatpak/ld.so.conf.d/runtime-002-org.freedesktop.Platform.VAAPI.Intel.conf --ro-bind-data 17 /run/flatpak/ld.so.conf.d/runtime-003-org.freedesktop.Platform.openh264.conf --proc /proc --unshare-pid --dir /tmp --dir /var/tmp --dir /run/host --dir /run/user/1000 --setenv XDG_RUNTIME_DIR /run/user/1000 --symlink ../run /var/run --ro-bind /sys/block /sys/block --ro-bind /sys/bus /sys/bus --ro-bind /sys/class /sys/class --ro-bind /sys/dev /sys/dev --ro-bind /sys/devices /sys/devices --ro-bind-try /proc/self/ns/user /run/.userns --symlink /etc/timezone /var/db/zoneinfo --ro-bind-data 21 /etc/passwd --ro-bind-data 22 /etc/group --ro-bind-data 23 /etc/pkcs11/pkcs11.conf --ro-bind /etc/machine-id /etc/machine-id --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/ca-certificates.conf /etc/ca-certificates.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/e2scrub.conf /etc/e2scrub.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/issue /etc/issue --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/issue.net /etc/issue.net --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/krb5.conf /etc/krb5.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/ld.so.cache /etc/ld.so.cache --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/ld.so.conf /etc/ld.so.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/mke2fs.conf /etc/mke2fs.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/moduli /etc/moduli --symlink ../../proc/self/mounts /etc/mtab --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/nsswitch.conf /etc/nsswitch.conf --symlink ../usr/lib/os-release /etc/os-release --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/protocols /etc/protocols --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/rc_maps.cfg /etc/rc_maps.cfg --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/rpc /etc/rpc --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/services /etc/services --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/ssh_config /etc/ssh_config --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/vdpau_wrapper.cfg /etc/vdpau_wrapper.cfg --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/wgetrc /etc/wgetrc --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/xattr.conf /etc/xattr.conf --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/alsa /etc/alsa --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/dbus-1 /etc/dbus-1 --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/fonts /etc/fonts --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/geoclue /etc/geoclue --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/gtk-3.0 /etc/gtk-3.0 --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/profile.d /etc/profile.d --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/pulse /etc/pulse --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/rc_keymaps /etc/rc_keymaps --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/ssl /etc/ssl --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/xdg /etc/xdg --ro-bind /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.38/670bab06de70a849266b2e81f78dbf6fb68ecc55fc91bfcad062f4bf168daa53/files/etc/xml /etc/xml --bind /home/erazemk/.var/app/com.st.STM32CubeIDE/cache /var/cache --bind /home/erazemk/.var/app/com.st.STM32CubeIDE/data /var/data --bind /home/erazemk/.var/app/com.st.STM32CubeIDE/config /var/config --bind /home/erazemk/.var/app/com.st.STM32CubeIDE/cache/tmp /var/tmp --symlink usr/bin /bin --symlink usr/lib /lib --symlink usr/lib64 /lib64 --symlink usr/sbin /sbin --ro-bind /usr/share/zoneinfo /usr/share/zoneinfo --symlink ../usr/share/zoneinfo/Europe/Ljubljana /etc/localtime --ro-bind-data 24 /etc/timezone --seccomp 25 --ro-bind /run/user/1000/.flatpak-helper/monitor /run/host/monitor --symlink /run/host/monitor/resolv.conf /etc/resolv.conf --symlink /run/host/monitor/host.conf /etc/host.conf --symlink /run/host/monitor/hosts /etc/hosts --ro-bind-data 26 /etc/pkcs11/modules/p11-kit-trust.module --ro-bind /run/user/1000/.flatpak-helper/pkcs11-flatpak-22811 /run/user/1000/p11-kit/pkcs11 --ro-bind-data 27 /etc/ld.so.conf --ro-bind-data 18 /etc/ld.so.cache --ro-bind /run/user/1000/.flatpak/2363508423 /run/user/1000/.flatpak/2363508423 --lock-file /run/user/1000/.flatpak/2363508423/.ref --file 29 /.flatpak-info --ro-bind-data 30 /.flatpak-info --symlink ../../../.flatpak-info /run/user/1000/flatpak-info --info-fd 31 --bind /run/user/1000/doc/by-app/com.st.STM32CubeIDE /run/user/1000/doc --dev-bind /dev /dev --tmpfs /dev/shm --bind /run/user/1000/app/com.st.STM32CubeIDE /run/user/1000/app/com.st.STM32CubeIDE --bind /home /home --dir /home/erazemk --tmpfs /home/erazemk/.local/share/flatpak --tmpfs /home/erazemk/.var/app --bind /home/erazemk/.var/app/com.st.STM32CubeIDE /home/erazemk/.var/app/com.st.STM32CubeIDE --bind '/lost+found' '/lost+found' --bind /media /media --bind /mnt /mnt --bind /opt /opt --bind /run/media /run/media --bind /srv /srv --bind /usr /run/host/usr --symlink usr/bin /run/host/bin --symlink usr/lib /run/host/lib --symlink usr/lib64 /run/host/lib64 --symlink usr/sbin /run/host/sbin --bind /etc /run/host/etc --ro-bind /home/erazemk/.config/user-dirs.dirs /home/erazemk/.var/app/com.st.STM32CubeIDE/config/user-dirs.dirs --tmpfs /tmp/.X11-unix --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X99 --ro-bind-data 33 /run/user/1000/Xauthority --ro-bind-data 32 /run/user/1000/pulse/config --ro-bind /run/user/1000/pulse/native /run/user/1000/pulse/native --dev-bind /dev/snd /dev/snd --ro-bind /run/user/1000/bus /run/user/1000/bus --ro-bind /run/user/1000/.dbus-proxy/a11y-bus-proxy-QL5TS0 /run/user/1000/at-spi-bus --sync-fd 35 --ro-bind /run/systemd/journal/socket /run/systemd/journal/socket --ro-bind /run/systemd/journal/stdout /run/systemd/journal/stdout --ro-bind /usr/share/fonts /run/host/fonts --ro-bind /usr/lib/fontconfig/cache /run/host/fonts-cache --tmpfs /run/host/user-fonts-cache --remount-ro /run/host/user-fonts-cache --ro-bind-data 34 /run/host/font-dirs.xml --ro-bind /usr/share/icons /run/host/share/icons --ro-bind /home/erazemk/.local/share/icons /run/host/user-share/icons --symlink /app/lib/debug/source /run/build --symlink /usr/lib/debug/source /run/build-runtime
F: Running 'bwrap --args 36 stm32cubeide'
```

**Comment by alpemwarrior** [comment]
I believe you can't run udevadm inside a flatpak and thus it fails to find a programmer. Why it is trying to parse every device node in /dev is beyond me.

**Comment by Maldus512** [comment]
I'm having the same problem. Does this mean that it's simply not possible to flash a device from the flatpak application?
